spring.application.name=ms-reservas
server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/reservas_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root123
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

whatsapp.token=EAASoYwbjyOABRXGx6ZAmper0Y1ePGLndZBBvJZCfmQBNwRJZAuRS4gA6hBKjQ0hYuFbJAX0pMWb1FDmXuUlXanpAB1AlGZBqVkTpvR4EcNIxY425ZA8VrARfXYMmZBMqQHWpl7eKiBdZBa1G73WZAkfvrz4be0tTEPkQCPbGNYnB6XCzHYZCwnDJcFaGSDZArTVnjPqLkO5tN81VQ4zs6E2ZCcmXu9WjWZBIcvFRGHMxwBdHOeBqg9h1r3RZBLagrKh9TG0yahiktl7qqZB0euujFqCNzXitAZDZD
whatsapp.phone.number.id=1027806413759148

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
