spring.application.name=ms-eureka
server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.wait-time-in-ms-when-sync-empty=0
spring.jpa.open-in-view=false
# ms-eureka - Sistema de Reservas de Tours Rio de Janeiro
